# Generated by Django 5.1.3 on 2024-11-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Core Product',
                'verbose_name_plural': 'Core Products',
                'db_table': 'core_coreproduct',
            },
        ),
    ]
